"""Dev-only: ask the firmware for each built-in voice's Design Voice
defaults and legal ranges, and emit a Python table for the driver.

`[:dv listall]` makes the ROM print its own parameter block over the host
link, so these numbers come from the firmware itself rather than from the
OCR'd manual (whose ranges turned out to be wrong for several parameters
-- e.g. it gives smoothness as 0..24 dB where the ROM reports 0..100 %).

Needed because NVDA's sliders have to be *relative* to the selected
voice: 50% must mean "this voice's default", or the slider jumps
discontinuously around its midpoint when a voice's default sits far from
the middle of the absolute range (very audible on Huge Harry's low pitch).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "addon" / "synthDrivers" / "dectalkDtc01"))

from emu.native import NativeMachine  # noqa: E402
from protocol import commands as dtcmd  # noqa: E402

SILENCE = 120
LINE = re.compile(r"^\s*([a-z][a-z0-9]{0,3})\s+(-?\d+)\s*\S*\s*\(\s*(-?\d+)\s*\.\.\s*(-?\d+)\s*\)")


def settle(m):
    heard = quiet = lead = 0
    heard = False
    for _ in range(300):
        b = m.run_block(1000)
        if m.peak_of(b) >= SILENCE:
            heard, quiet = True, 0
            continue
        if not heard:
            lead += 1
            if lead >= 60 and m.is_idle:
                return
            continue
        quiet += 1
        if quiet >= 4 and m.is_idle:
            return


def query(voiceKey, firmware="v20"):
    # Pinned to v2.0, not left to $DTC01_ROM_VERSION: v1.8 has no Dennis or
    # Wendy and silently keeps the current voice for an unknown [:n_] code, so
    # querying it would emit Paul's numbers under their names.
    m = NativeMachine(str(ROOT / "roms_extracted"), rom_version=firmware)
    settle(m)
    m.read_host_tx()
    m.feed_text(f"{dtcmd.voice_command(voiceKey)}[:dv listall]\r".encode("ascii"))
    for _ in range(200):
        m.run_block(1000)
    text = m.read_host_tx().decode("ascii", "replace")
    m.close()

    params = {}
    for line in text.splitlines():
        mo = LINE.match(line)
        if mo:
            name, val, lo, hi = mo.group(1), int(mo.group(2)), int(mo.group(3)), int(mo.group(4))
            params[name] = (val, lo, hi)
    return params


def main() -> int:
    table = {}
    for key in dtcmd.VOICES:
        params = query(key)
        table[key] = params
        print(f"{key:8s} {len(params):2d} params  "
              f"ap={params.get('ap', ('?',))[0]} hs={params.get('hs', ('?',))[0]} "
              f"pr={params.get('pr', ('?',))[0]} ri={params.get('ri', ('?',))[0]} "
              f"br={params.get('br', ('?',))[0]} sm={params.get('sm', ('?',))[0]}")

    wanted = ["ap", "pr", "hs", "br", "ri", "sm", "la", "as"]
    print()
    print("# Generated by tools/dump_voice_defaults.py -- queried from the ROM")
    print("# via [:dv listall]. value, min, max per parameter, per voice.")
    print("VOICE_PARAM_DEFAULTS = {")
    for key, params in table.items():
        items = ", ".join(
            f'"{p}": {params[p]}' for p in wanted if p in params)
        print(f'\t"{key}": {{{items}}},')
    print("}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
